# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20170518_1234'),
        ('quest', '0003_auto_20170518_0805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together=set([('rank', 'descr')]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('quest', 'question')]),
        ),
    ]
