# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(verbose_name='firstname')),
                ('lastname', models.TextField(verbose_name='lastname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.Planet'),
        ),
    ]
