# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('prev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ranking.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='RankRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankapplicant_set', to='reception.Person')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rankmaster_set', to='reception.Person')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ranking.Rank')),
            ],
        ),
    ]
