# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20170518_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=25, verbose_name='name'),
        ),
    ]
