# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20170518_1541'),
        ('ranking', '0006_auto_20170518_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankregister',
            name='applicant',
        ),
        migrations.AddField(
            model_name='rankregister',
            name='junior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rankjunior_set', to='reception.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rankregister',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rankmentor_set', to='reception.Person'),
        ),
    ]
