# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20170518_1541'),
        ('ranking', '0007_auto_20170518_1620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankregister',
            unique_together=set([('junior', 'rank')]),
        ),
    ]
