# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_auto_20170518_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ap', 'applicant'), ('jr', 'junior')], max_length=2, unique=True, verbose_name='state')),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ranking.Rank')),
            ],
        ),
    ]
