# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_rankpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankpreset',
            name='limit',
            field=models.SmallIntegerField(default=3, verbose_name='limit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rankregister',
            name='junior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='juniors', to='reception.Person'),
        ),
        migrations.AlterField(
            model_name='rankregister',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentors', to='reception.Person'),
        ),
    ]
